name: Deploy Database to EC2

on:
  workflow_dispatch:

jobs:
  deploy-sql:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy SQL files to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "db/*.sql"
          target: "/tmp/sql-files"
          port: 22
          debug: true

      - name: Execute SQL files in PostgreSQL container
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker ps | grep postgresql-dev || {
              echo "Container postgresql-dev not running" >&2
              exit 1
            }

            docker cp /tmp/sql-files/. postgresql-dev:/tmp/

            docker exec postgresql-dev ls -l /tmp/db/

            for sqlfile in /tmp/db/*.sql; do
              filename=$(basename "$sqlfile")
              echo "Executing $filename..."
              docker exec -e PGPASSWORD=${{ secrets.POSTGRES_PASSWORD }} postgresql-dev \
                psql -U ${{ secrets.POSTGRES_USER }} \
                -d ${{ secrets.POSTGRES_DB }} \
                -f "/tmp/db/$filename.sql"
            done
